name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S optimizations/inlining

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Run default_inline benchmark
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ./inlining 1000 3 default_results.csv

    - name: Run forced_inline benchmark
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        cmake -B . -DFORCE_INLINE=ON ..
        cmake --build . --config ${{ matrix.build_type }}
        ./inlining 1000 3 force_results.csv

    - name: Run no_inline benchmark
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        cmake -B . -DNO_INLINE=ON ..
        cmake --build . --config ${{ matrix.build_type }}
        ./inlining 1000 3 noinline_results.csv

    - name: Verify result files
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        test -f default_results.csv || (echo "❌ default_results.csv missing" && exit 1)
        test -f force_results.csv || (echo "❌ force_results.csv missing" && exit 1)
        test -f noinline_results.csv || (echo "❌ noinline_results.csv missing" && exit 1)
        echo "✅ All output files present."
