name: Short-String-Optimization (CMake • multi-platform)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:          [ubuntu-latest, windows-latest]
        build_type:  [Release]
        c_compiler:  [gcc, clang, cl]
        include:
          #── Windows / MSVC
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          #── Ubuntu / GCC
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          #── Ubuntu / Clang
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    # ───────────── checkout ───────────────────────────────────────────────
    - uses: actions/checkout@v4

    # ───────────── configure ─────────────────────────────────────────────
    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S .

    # ───────────── build ─────────────────────────────────────────────────
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    # ───────────── run benchmark ─────────────────────────────────────────
    - name: Run benchmark
      working-directory: build
      shell: bash
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          ./Release/sso.exe 1000000 > sso_output.txt
        else
          ./sso 1000000 > sso_output.txt
        fi

    # ───────────── verify output ─────────────────────────────────────────
    - name: Verify that output file exists
      working-directory: build
      shell: bash
      run: |
        [[ -f sso_output.txt ]] || { echo "❌ sso_output.txt not found"; exit 1; }
        head -n 8 sso_output.txt    # show a snippet in the job log
